In [26]:
#Importando pandas
import pandas as pd

In [27]:
#Creando data frame
df_animes = pd.read_csv('dataset/anime.csv',sep='\t',header=0,names=['Anime_id', 'Anime_url', 'Title', 'Synopsis', 'Main_pic', 'Type', 'Source_type', 'Num_episodes', 'Status', 'Start_date', 'End_date', 'Season', 'Studios', 'Genres', 'Score', 'Score_count', 'Score_rank', 'Popularity_rank', 'Members_count', 'Favorites_count', 'Watching_count', 'Completed_count', 'On_hold_count', 'Dropped_count', 'Plan_to_watch_count', 'Total_count', 'Score_10_count', 'Score_09_count', 'Score_08_count', 'Score_07_count', 'Score_06_count', 'Score_05_count', 'Score_04_count', 'Score_03_count', 'Score_02_count', 'Score_01_count', 'Clubs', 'Pics'])
df_animes.head(2)

,Anime_id,Anime_url,Title,Synopsis,Main_pic,Type,Source_type,Num_episodes,Status,Start_date,...,Score_08_count,Score_07_count,Score_06_count,Score_05_count,Score_04_count,Score_03_count,Score_02_count,Score_01_count,Clubs,Pics
0,2366,https://myanimelist.net/anime/2366/Touma_Kishi...,Touma Kishinden Oni,Shuramaru is hated and feared by the villagers...,https://cdn.myanimelist.net/images/anime/9/829...,TV,Game,25.0,Finished Airing,1995-10-05 00:00:00,...,0,0,0,0,0,0,0,0,14045|10778|342,https://cdn.myanimelist.net/images/anime/9/544...
1,4940,https://myanimelist.net/anime/4940/Sabaku_no_K...,Sabaku no Kaizoku! Captain Kuppa,"Sometime in the future, the world was complete...",https://cdn.myanimelist.net/images/anime/9/736...,TV,Manga,26.0,Finished Airing,2001-08-13 00:00:00,...,0,0,0,0,0,0,0,0,8494,https://cdn.myanimelist.net/images/anime/9/736...

In [28]:
#Veamos el tamaño del Data Frame
df_animes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13379 entries, 0 to 13378
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Anime_id             13379 non-null  int64
 1   Anime_url            13379 non-null  object
 2   Title                13379 non-null  object
 3   Synopsis             13375 non-null  object
 4   Main_pic             13379 non-null  object
 5   Type                 13379 non-null  object
 6   Source_type          13379 non-null  object
 7   Num_episodes         12948 non-null  float64
 8   Status               13379 non-null  object
 9   Start_date           13198 non-null  object
 10  End_date             12799 non-null  object
 11  Season               4280 non-null   object
 12  Studios              10343 non-null  object
 13  Genres               13379 non-null  object
 14  Score                10714 non-null  float64
 15  Score_count          10714 non-null  float64
 16  Score_rank           9465 non-null   float64
 17  Popularity_rank      13379 non-null  int64
 18  Members_count        13379 non-null  int64
 19  Favorites_count      13379 non-null  int64
 20  Watching_count       13379 non-null  int64
 21  Completed_count      13379 non-null  int64
 22  On_hold_count        13379 non-null  int64
 23  Dropped_count        13379 non-null  int64
 24  Plan_to_watch_count  13379 non-null  int64
 25  Total_count          13379 non-null  int64
 26  Score_10_count       13379 non-null  int64
 27  Score_09_count       13379 non-null  int64
 28  Score_08_count       13379 non-null  int64
 29  Score_07_count       13379 non-null  int64
 30  Score_06_count       13379 non-null  int64
 31  Score_05_count       13379 non-null  int64
 32  Score_04_count       13379 non-null  int64
 33  Score_03_count       13379 non-null  int64
 34  Score_02_count       13379 non-null  int64
 35  Score_01_count       13379 non-null  int64
 36  Clubs                11618 non-null  object
 37  Pics                 13379 non-null  object
dtypes: float64(4), int64(20), object(14)
memory usage: 3.9+ MB

In [29]:
df_animes.memory_usage(deep=True)

Index                      132
Anime_id                107032
Anime_url              1508186
Title                  1023656
Synopsis               8136737
Main_pic               1374409
Type                    703186
Source_type             750833
Num_episodes            107032
Status                  855782
Start_date              903256
End_date                888892
Season                  545454
Studios                 730910
Genres                  966514
Score                   107032
Score_count             107032
Score_rank              107032
Popularity_rank         107032
Members_count           107032
Favorites_count         107032
Watching_count          107032
Completed_count         107032
On_hold_count           107032
Dropped_count           107032
Plan_to_watch_count     107032
Total_count             107032
Score_10_count          107032
Score_09_count          107032
Score_08_count          107032
Score_07_count          107032
Score_06_count          107032
Score_05_count          107032
Score_04_count          107032
Score_03_count          107032
Score_02_count          107032
Score_01_count          107032
Clubs                  1685112
Pics                   2498474
dtype: int64

In [30]:
df_animes.describe()

,Anime_id,Num_episodes,Score,Score_count,Score_rank,Popularity_rank,Members_count,Favorites_count,Watching_count,Completed_count,...,Score_10_count,Score_09_count,Score_08_count,Score_07_count,Score_06_count,Score_05_count,Score_04_count,Score_03_count,Score_02_count,Score_01_count
count,13379.000000,12948.000000,10714.000000,1.071400e+04,9465.000000,13379.000000,1.337900e+04,13379.000000,1.337900e+04,1.337900e+04,...,13379.000000,13379.000000,13379.000000,13379.000000,13379.000000,13379.000000,13379.000000,13379.000000,13379.000000,13379.000000
mean,23185.896928,12.327850,6.561258,3.728666e+04,5544.653883,7889.506017,5.787081e+04,684.553629,3.605542e+03,3.700065e+04,...,4221.423425,5386.886314,7549.294267,6518.632110,3179.698034,1575.021676,707.784663,325.840795,192.172958,202.672995
std,16646.297648,44.955752,0.985277,1.229652e+05,3528.083235,5333.044230,1.831933e+05,5225.720400,1.867524e+04,1.346181e+05,...,25155.586913,27136.981672,29747.833821,20844.007676,9392.467902,4696.911975,2534.335234,1268.534304,821.238810,1029.747375
min,1.000000,1.000000,1.850000,1.010000e+02,1.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5433.000000,1.000000,6.020000,8.315000e+02,2483.000000,3380.500000,9.270000e+02,1.000000,3.500000e+01,2.570000e+02,...,10.000000,4.000000,11.000000,28.000000,37.500000,36.000000,15.000000,8.000000,5.000000,7.000000
50%,27417.000000,3.000000,6.650000,3.486500e+03,5208.000000,7094.000000,5.239000e+03,8.000000,2.190000e+02,2.368000e+03,...,114.000000,99.000000,221.000000,400.000000,357.000000,229.000000,93.000000,47.000000,28.000000,30.000000
75%,37771.000000,12.000000,7.250000,1.989225e+04,8394.000000,11694.500000,3.048950e+04,69.000000,1.123000e+03,1.575850e+04,...,922.500000,1088.000000,2318.000000,3144.500000,1930.000000,1019.500000,395.500000,180.000000,103.000000,102.000000
max,51333.000000,3057.000000,9.050000,2.380891e+06,12406.000000,19552.000000,3.329298e+06,197551.000000,1.225976e+06,2.905060e+06,...,875328.000000,699881.000000,613059.000000,387608.000000,238248.000000,155460.000000,100101.000000,53437.000000,30218.000000,43363.000000

In [31]:
#Obteniendo headers de columnas
df_animes.columns

Index(['Anime_id', 'Anime_url', 'Title', 'Synopsis', 'Main_pic', 'Type',
       'Source_type', 'Num_episodes', 'Status', 'Start_date', 'End_date',
       'Season', 'Studios', 'Genres', 'Score', 'Score_count', 'Score_rank',
       'Popularity_rank', 'Members_count', 'Favorites_count', 'Watching_count',
       'Completed_count', 'On_hold_count', 'Dropped_count',
       'Plan_to_watch_count', 'Total_count', 'Score_10_count',
       'Score_09_count', 'Score_08_count', 'Score_07_count', 'Score_06_count',
       'Score_05_count', 'Score_04_count', 'Score_03_count', 'Score_02_count',
       'Score_01_count', 'Clubs', 'Pics'],
      dtype='object')

### Ejemplo de si contiene una cadena exacta
df2[df2["E"].isin(["two", "four"])]

Quiero las columnas de: 'title','genres','num_episodes','type','anime_url','status','start_date','end_date','score','score_rank','status','watching_count'

In [32]:
#Creando my Data Frame
Genres = list(df_animes['Genres'].drop_duplicates())
Genres
split_genres = [genre.split('|') for genre in Genres]
#len(split_genres) 
# Me arroja una lista de 3542 elementos que contienen 
# otras listas dentro


# Separar los géneros y obtener una lista aplanada
flattened_genres = [item for sublist in split_genres for item in sublist]

# Convertir la lista a un conjunto para obtener géneros únicos
Unique_genres = list(set(flattened_genres))
#Ordene la lista
Unique_genres.sort()
#Cree un data frame con los distintos tipos de generos 
df_Genres = pd.DataFrame(Unique_genres, columns=['Genres'])
df_Genres.head(2)

      Genres
0     Action
1  Adventure

In [33]:
#Estableciendo que Columnas quiero del data set principal
Columns= ['Score','Title', 'Genres', 'Num_episodes', 'Type', 'Status', 'Start_date', 'End_date','Status', 'Watching_count']

In [34]:
#Creando mi DataFrame basado en las columnas importantes
my_df_animes =df_animes.loc[:,Columns]

In [35]:
#Imprimiendo el DataFrame
my_df_animes.head(5)

,Score,Title,Genres,Num_episodes,Type,Status,Start_date,End_date,Status,Watching_count
0,NaN,Touma Kishinden Oni,Supernatural,25.0,TV,Finished Airing,1995-10-05 00:00:00,1996-03-21 00:00:00,Finished Airing,61
1,NaN,Sabaku no Kaizoku! Captain Kuppa,Action|Adventure,26.0,TV,Finished Airing,2001-08-13 00:00:00,2002-02-11 00:00:00,Finished Airing,26
2,NaN,On Air Dekinai!,Comedy,12.0,TV,Currently Airing,2022-01-10 00:00:00,2022-03-28 00:00:00,Currently Airing,203
3,NaN,Uchi no 3 Shimai,Comedy|Slice of Life,102.0,TV,Finished Airing,2008-04-08 00:00:00,2010-03-30 00:00:00,Finished Airing,45
4,NaN,Running Man,Action|Adventure|Kids,48.0,TV,Finished Airing,2017-07-29 00:00:00,2018-10-12 00:00:00,Finished Airing,23

In [36]:
#Esta función solo especifica si tiene la palabra Romance, 
#pero quiero otras combinaciones
my_df_animes[my_df_animes["Genres"].isin(['Romance'])]

,Score,Title,Genres,Num_episodes,Type,Status,Start_date,End_date,Status,Watching_count
2081,6.27,Okusama wa Mahou Shoujo,Romance,13.0,TV,Finished Airing,2005-07-04 00:00:00,2005-09-26 00:00:00,Finished Airing,401
4466,NaN,Shiohi Girls: Vongole Bianco,Romance,48.0,ONA,Finished Airing,2019-11-13 00:00:00,2020-04-24 00:00:00,Finished Airing,28
4536,NaN,Wedding Park,Romance,2.0,ONA,Finished Airing,2018-12-10 00:00:00,2019-01-08 00:00:00,Finished Airing,27
4906,NaN,Hen Chun Hen Aimei,Romance,NaN,ONA,Not yet aired,NaN,NaN,Not yet aired,0
4949,NaN,Bokutachi no Kidzuki-hen,Romance,1.0,ONA,Finished Airing,2019-09-11 00:00:00,2019-09-11 00:00:00,Finished Airing,17
5160,5.55,Ogaki Matsuri ni Ikou yo!,Romance,1.0,ONA,Finished Airing,2020-03-30 00:00:00,2020-03-30 00:00:00,Finished Airing,52
5445,5.60,Monogatari no Aru Satou,Romance,1.0,ONA,Finished Airing,2017-10-10 00:00:00,2017-10-10 00:00:00,Finished Airing,16
5743,6.04,Choujuu Giga,Romance,3.0,ONA,Finished Airing,2016-03-14 00:00:00,2016-11-17 00:00:00,Finished Airing,89
6322,2.46,Ai (ONA),Romance,1.0,ONA,Finished Airing,2012-08-10 00:00:00,2012-08-10 00:00:00,Finished Airing,35
7005,6.77,To Heart 2 AD Plus,Romance,2.0,OVA,Finished Airing,2009-04-24 00:00:00,2009-10-07 00:00:00,Finished Airing,215
7861,3.83,Steady x Study,Romance,1.0,OVA,Finished Airing,2004-05-26 00:00:00,2004-05-26 00:00:00,Finished Airing,42
9356,NaN,Cherry and Virgin,Romance,1.0,Movie,Not yet aired,2022-03-20 00:00:00,NaN,Not yet aired,0
12485,6.75,Ushinawareta Mirai wo Motomete: Ushinawareta N...,Romance,1.0,Special,Finished Airing,2015-08-20 00:00:00,2015-08-20 00:00:00,Finished Airing,229
12535,6.89,Koitabi: True Tours Nanto,Romance,6.0,Special,Finished Airing,2013-04-28 00:00:00,2013-04-28 00:00:00,Finished Airing,739
12909,7.22,Amagami SS+ Plus: Extra Episode+ Plus,Romance,6.0,Special,Finished Airing,2012-04-04 00:00:00,2012-09-05 00:00:00,Finished Airing,739
13131,6.57,Amagami SS+ Plus Picture Drama,Romance,2.0,Special,Finished Airing,2012-10-03 00:00:00,2012-10-03 00:00:00,Finished Airing,392

## ¿Cómo crear un Excel?

#### Creando un set nulo para hacer un archivo en blanco de Excel para después cargar y modificarlo.
```python
import pandas as pd

# Creando datos nulos
data = {}
df_nulo = pd.DataFrame(data)

# Nombre del archivo Excel
Nombre = 'Nombre.xlsx'

# Crea un archivo Excel con los parámetros dados
df_nulo.to_excel(Nombre, index=False)

# Cargar y modificar el archivo
with pd.ExcelWriter(Nombre, mode='a', engine='openpyxl') as writer:
    # Adjunta los DataFrames a las hojas existentes en el archivo
    df1 = pd.DataFrame({'A': [1, 2, 3]})
    df2 = pd.DataFrame({'B': [4, 5, 6]})
    df1.to_excel(writer, sheet_name='Sheet1', index=False)
    df2.to_excel(writer, sheet_name='Sheet2', index=False)

print("Datos escritos en", Nombre)
```

In [37]:
#Este tipo de busqueda es más precisa y abierta
my_df_animes[(my_df_animes['Genres'].str.contains('Romance'))&(my_df_animes['Genres'].str.contains('Drama'))]

#Filtrando datos y obteniendo animes 
#Obteniendo animes de Romance
filter_option = (my_df_animes['Genres'].str.contains('Romance'))&(my_df_animes['Genres'].str.contains('Drama'))
df_Romance=my_df_animes[filter_option]
#Ordenando por puntuación
df_Romance=df_Romance.sort_values('Score',ascending=False) 
# Reemplazar el índice con una secuencia que comience en 1
df_Romance.reset_index(drop=True, inplace=True)
df_Romance.index = df_Romance.index + 1

#Obteniendo animes de Música
filter_option = (my_df_animes['Genres'].str.contains('Music'))
df_Music = my_df_animes[filter_option]
#Ordenando por puntuación
df_Music=df_Music.sort_values('Score',ascending=False)
# Reemplazar el índice con una secuencia que comience en 1
df_Music.reset_index(drop=True, inplace=True)
df_Music.index = df_Music.index + 1

#Obteniendo solo música
df_OnlyMusic = my_df_animes[my_df_animes["Genres"].isin(['Music'])]
#Ordenando por puntuación
df_OnlyMusic = df_OnlyMusic.sort_values('Score',ascending=False)
#Reemplazando indices
df_OnlyMusic.reset_index(drop=True, inplace=True)
df_OnlyMusic.index = df_OnlyMusic.index + 1

#Sacando archivo animes xlxs
#df_animes.to_excel('Animes.xlsx',sheet_name='Animes')

# Nombre del archivo Excel
Nombre = 'my_animes_dataset.xlsx'

# Crea un archivo Excel con los parámetros dados
    #El indice de Genres empezaba en 0 
    #lo cambié para que empezará en 1
df_Genres.index = df_Genres.index + 1
df_Genres.to_excel(Nombre,sheet_name='Anime Genres')

# Cargar y modificar el archivo
    #Exportando datos a Excel
with pd.ExcelWriter(Nombre, mode='a', engine='openpyxl') as writer:
    # Adjunta los DataFrames a las hojas existentes en el archivo    
    df_Romance.to_excel(writer,sheet_name='Romance')
    df_OnlyMusic.to_excel(writer,sheet_name='Only Music')
    df_Music.to_excel(writer,sheet_name='Music')

print("Datos escritos en", Nombre)

Datos escritos en my_animes_dataset.xlsx

## Ajustar contenido de una hoja de Excel

```python
import pandas as pd
from openpyxl import load_workbook

# Nombre del archivo Excel
nombre_archivo = 'datos.xlsx'

# Cargar el archivo Excel
wb = load_workbook(nombre_archivo)

# Iterar sobre cada hoja del archivo Excel
for sheet_name in wb.sheetnames:
    # Obtener la hoja actual
    ws = wb[sheet_name]
    
    # Iterar sobre cada columna de la hoja actual
    for col in ws.columns:
        max_length = 0
        column = col[0].column_letter  # Obtener la letra de la columna
        for cell in col:
            try:  # Tratar de obtener la longitud del valor de la celda
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        
        # Ajustar el ancho de la columna
        adjusted_width = (max_length + 2) * 1.2  # Ajuste adicional para mejor legibilidad
        ws.column_dimensions[column].width = adjusted_width

# Guardar los cambios en el archivo Excel
wb.save(nombre_archivo)

```

In [38]:
import pandas as pd
from openpyxl import load_workbook

# Nombre del archivo Excel

nombre_archivo = Nombre
##Para ordenar archivos
#nombre_archivo = 'Animes.xlsx'
# Cargar el archivo Excel
wb = load_workbook(nombre_archivo)

# Iterar sobre cada hoja del archivo Excel
for sheet_name in wb.sheetnames:
    # Obtener la hoja actual
    ws = wb[sheet_name]
    
    # Iterar sobre cada columna de la hoja actual
    for col in ws.columns:
        max_length = 0
        column = col[0].column_letter  # Obtener la letra de la columna
        for cell in col:
            try:  # Tratar de obtener la longitud del valor de la celda
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        
        # Ajustar el ancho de la columna
        adjusted_width = (max_length + 2) * 1.1  # Ajuste adicional para mejor legibilidad
        ws.column_dimensions[column].width = adjusted_width

# Guardar los cambios en el archivo Excel
wb.save(nombre_archivo)